/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author edyne
 */
public class AgregarClienteFrame extends javax.swing.JInternalFrame {

   
    private JTextField nombreField;
    private JTextField apellidoField;
    private JTextField direccionField;
    private JTextField telefonoField;
    private JTextField emailField;
    private JTextField ciudadField;
    private JTextField estadoField;
    private JTextField codigoPostalField;

    private JButton guardarButton;
    private JButton cancelarButton;
    private JButton limpiarButton;
    private JButton salirButton;
    public AgregarClienteFrame() {
        initComponents();
         nombreField = new JTextField();
        apellidoField = new JTextField();
        direccionField = new JTextField();
        telefonoField = new JTextField();
        emailField = new JTextField();
        ciudadField = new JTextField();
        estadoField = new JTextField();
        codigoPostalField = new JTextField();

        guardarButton = new JButton("Guardar");
        cancelarButton = new JButton("Cancelar");
        limpiarButton = new JButton("Limpiar");
        salirButton = new JButton("Salir");

        // Aquí agregas los componentes al frame, usando el layout que prefieras
        setLayout(new java.awt.GridLayout(9, 2)); // Por ejemplo, un GridLayout de 9 filas y 2 columnas

        add(new JLabel("Nombre:"));
        add(nombreField);
        add(new JLabel("Apellido:"));
        add(apellidoField);
        add(new JLabel("Dirección:"));
        add(direccionField);
        add(new JLabel("Teléfono:"));
        add(telefonoField);
        add(new JLabel("Email:"));
        add(emailField);
        add(new JLabel("Ciudad:"));
        add(ciudadField);
        add(new JLabel("Estado:"));
        add(estadoField);
        add(new JLabel("Código Postal:"));
        add(codigoPostalField);

        add(guardarButton);
        add(cancelarButton);
        add(limpiarButton);
        add(salirButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
