package Vista;

import Configuracion.Conexion;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class FrmCliente extends javax.swing.JInternalFrame {

    public FrmCliente() {
        initComponents();

        // Aquí agregas los componentes al frame, usando el layout que prefieras
        setLayout(new java.awt.GridLayout(9, 2)); // Por ejemplo, un GridLayout de 9 filas y 2 columnas

        add(new JLabel("Nombre:"));
        add(nombreFieldd1);
        add(new JLabel("Apellido:"));
        add(apellidoFieldd);
        add(new JLabel("Dirección:"));
        add(direccionFieldd);
        add(new JLabel("Teléfono:"));
        add(telefonoFieldd);
        add(new JLabel("Email:"));
        add(emailFieldd);
        add(new JLabel("Ciudad:"));
        add(ciudadFieldd);
        add(new JLabel("Estado:"));
        add(estadoFieldd);
        add(new JLabel("Código Postal:"));
        add(codigoPostalFieldd);

        add(guardarButtonn);
        add(cancelarButtonn);
        add(limpiarButtonn);
        add(salirButtonn);
        guardarButtonn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                guardarCliente();
            }
        });

        cancelarButtonn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cancelar();
            }
        });

        limpiarButtonn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                limpiarCampos();
            }
        });

        salirButtonn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                salir();
            }
        });
        
        
    }

    private void guardarCliente() {
        String nombre = nombreFieldd1.getText();
        String apellido = apellidoFieldd.getText();
        String direccion = direccionFieldd.getText();
        String telefono = telefonoFieldd.getText();
        String email = emailFieldd.getText();
        String ciudad = ciudadFieldd.getText();
        String estado = estadoFieldd.getText();
        String codigoPostal = codigoPostalFieldd.getText();

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = Conexion.HacerConexion();
            if (conn != null) {
                String sql = "INSERT INTO clientes (nombre, apellido, direccion, telefono, email, ciudad, estado, codigo_postal) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                stmt = conn.prepareStatement(sql);
                stmt.setString(1, nombre);
                stmt.setString(2, apellido);
                stmt.setString(3, direccion);
                stmt.setString(4, telefono);
                stmt.setString(5, email);
                stmt.setString(6, ciudad);
                stmt.setString(7, estado);
                stmt.setString(8, codigoPostal);

                stmt.executeUpdate();
                System.out.println("Cliente guardado: " + nombre + " " + apellido);
            } else {
                System.out.println("Error de conexión a la base de datos");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    // Método para cancelar la operación
    private void cancelar() {
        System.out.println("Operación cancelada");
    }

    // Método para limpiar los campos del formulario
    private void limpiarCampos() {
        nombreFieldd1.setText("");
        apellidoFieldd.setText("");
        direccionFieldd.setText("");
        telefonoFieldd.setText("");
        emailFieldd.setText("");
        ciudadFieldd.setText("");
        estadoFieldd.setText("");
        codigoPostalFieldd.setText("");
    }

    // Método para cerrar el frame
    private void salir() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirButtonn = new javax.swing.JButton();
        guardarButtonn = new javax.swing.JButton();
        cancelarButtonn = new javax.swing.JButton();
        limpiarButtonn = new javax.swing.JButton();
        codigoPostalFieldd = new javax.swing.JTextField();
        nombreFieldd1 = new javax.swing.JTextField();
        apellidoFieldd = new javax.swing.JTextField();
        direccionFieldd = new javax.swing.JTextField();
        telefonoFieldd = new javax.swing.JTextField();
        emailFieldd = new javax.swing.JTextField();
        ciudadFieldd = new javax.swing.JTextField();
        estadoFieldd = new javax.swing.JTextField();
        nombreFieldd8 = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salirButtonn.setText("jButton1");
        getContentPane().add(salirButtonn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 130, 40));

        guardarButtonn.setText("jButton1");
        getContentPane().add(guardarButtonn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 130, 40));

        cancelarButtonn.setText("jButton1");
        getContentPane().add(cancelarButtonn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 40));

        limpiarButtonn.setText("jButton1");
        getContentPane().add(limpiarButtonn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 130, 40));
        getContentPane().add(codigoPostalFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 140, 30));
        getContentPane().add(nombreFieldd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, 30));
        getContentPane().add(apellidoFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, 30));
        getContentPane().add(direccionFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 140, 30));
        getContentPane().add(telefonoFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 30));
        getContentPane().add(emailFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, 30));
        getContentPane().add(ciudadFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, 30));
        getContentPane().add(estadoFieldd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, 30));
        getContentPane().add(nombreFieldd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoFieldd;
    private javax.swing.JButton cancelarButtonn;
    private javax.swing.JTextField ciudadFieldd;
    private javax.swing.JTextField codigoPostalFieldd;
    private javax.swing.JTextField direccionFieldd;
    private javax.swing.JTextField emailFieldd;
    private javax.swing.JTextField estadoFieldd;
    private javax.swing.JButton guardarButtonn;
    private javax.swing.JButton limpiarButtonn;
    private javax.swing.JTextField nombreFieldd1;
    private javax.swing.JTextField nombreFieldd8;
    private javax.swing.JButton salirButtonn;
    private javax.swing.JTextField telefonoFieldd;
    // End of variables declaration//GEN-END:variables
}
