/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import AccesoDatos.DAO_CuentasPorCobrar;
import Modelo.CuentaPorCobrar;
import Procesos.Mensajes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 *
 * @author Pool
 */
public class ReportesPorCobrar  extends javax.swing.JInternalFrame implements ActionListener { 

    /**
     * Creates new form ReportesPorCobrar
     */
    public ReportesPorCobrar() {
        initComponents();
         jButton1.addActionListener(this); // Botón TXT
        jButton2.addActionListener(this);
    }
 public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jButton1) {
            generarReporteTXT();
        } else if (e.getSource() == jButton2) {
            generarReportePDF();
        }
    }
  private void generarReporteTXT() {
        DAO_CuentasPorCobrar dao = new DAO_CuentasPorCobrar();
        ArrayList<CuentaPorCobrar> cuentasPorCobrar = dao.ListarCuentaPorCobrar();

        try (PrintWriter pw = new PrintWriter(new FileWriter("reporte_cuentas_por_cobrar.txt"))) {
            for (CuentaPorCobrar cuenta : cuentasPorCobrar) {
                pw.println("ID Cliente: " + cuenta.getIdCliente());
                pw.println("Monto: " + cuenta.getMonto());
                pw.println("Fecha Emisión: " + cuenta.getFechaEmision());
                pw.println("Fecha Vencimiento: " + cuenta.getFechaVencimiento());
                pw.println("Estado: " + cuenta.getEstado());
                pw.println("-----------------------------");
            }
            pw.close();
            Mensajes.MostrarTexto("Reporte TXT generado correctamente.");
        } catch (IOException ex) {
            Mensajes.MostrarTexto("Error al generar reporte TXT: " + ex.getMessage());
        }
    }

    private void generarReportePDF() {
        DAO_CuentasPorCobrar dao = new DAO_CuentasPorCobrar();
        ArrayList<CuentaPorCobrar> cuentasPorCobrar = dao.ListarCuentaPorCobrar();

        try (PrintWriter pw = new PrintWriter(new FileWriter("reporte_cuentas_por_cobrar.pdf"))) {
            pw.println("ID Cliente\tMonto\tFecha Emisión\tFecha Vencimiento\tEstado");
            for (CuentaPorCobrar cuenta : cuentasPorCobrar) {
                pw.println(cuenta.getIdCliente() + "\t" + cuenta.getMonto() + "\t" + cuenta.getFechaEmision() + "\t" + cuenta.getFechaVencimiento() + "\t" + cuenta.getEstado());
            }
            pw.close();
            Mensajes.MostrarTexto("Reporte PDF generado correctamente.");
        } catch (IOException ex) {
            Mensajes.MostrarTexto("Error al generar reporte PDF: " + ex.getMessage());
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("TXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, 40));

        jButton2.setText("PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
